<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>DalSoft.RestClient.Benchmarks</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DalSoft.RestClient\DalSoft.RestClient.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.14.0" />
    <PackageReference Include="Flurl.Http" Version="4.0.2" />
    <PackageReference Include="Refit" Version="15.0.0" />
    <PackageReference Include="RestClient.Net" Version="7.2.1" />
    <PackageReference Include="RestSharp" Version="114.0.0" />
  </ItemGroup>

</Project>
